title: Jakub's Homepage
description: Hello.
collections:
  posts:
    output: true

remote_theme: pages-themes/primer@v0.6.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
